### ISSUE TITLE
Have to reboot to display the new pictures

### ISSUE THREAD

**Issue by walrus543** [UnevenSoftware/LeafPic#115]
Hi,
How to reproduce the issue:
1. With a file manager, create a new folder into your internal memory and copy some pictures
2. Open LeafPic
3. The pictures are not displayed

I have to reboot my phone to be able to see them.
Thank you.

Nexus 5 - Android 6.0.1.

**Comment by dnldsht** [comment]
which file manager are you using?
I tried with solid explorer with your same device an i get new pictures.
anyone else have this issue?

**Comment by walrus543** [comment]
Amaze File Manager or MiXplorer.
A few screenshots to show you the problem.
![screenshot_20160422-132618](https://cloud.githubusercontent.com/assets/5938828/14740369/a71e9422-088e-11e6-81ff-8b3eb630858a.png)
![screenshot_20160422-132627](https://cloud.githubusercontent.com/assets/5938828/14740370/a7213ce0-088e-11e6-9b37-e8999db4e907.png)
![screenshot_20160422-132637](https://cloud.githubusercontent.com/assets/5938828/14740371/a7225b8e-088e-11e6-97b6-c2fd208d7a71.png)

**Comment by iasgair** [comment]
I tried this with Amaze and the pictures were displayed in LeafPic immediately. 

However, when I deleted them in Amaze, the folder stayed in LeafPic. When clicking on it, it still displayed the right amount of pictures, but all with just grey icons. When clicking on one , an empty grey screen was shown (maybe grey because I use the dark theme. Also, menu bars were shown and details still had correct path).
To get rid of these remnants in LeafPic, I had to delete the folder in LeafPic again and then pull down to refresh. Refreshing before the deleting in LeafPic had no effect.
