### ISSUE TITLE
Add support to display photo location on a map

### ISSUE THREAD

**Issue by utack** [UnevenSoftware/LeafPic#133]
I guess this is kind of a huge request, but it would add a lot of value to the app.
Adding support to display where images were taken on a map would be a great feature.
[osmdroid](https://wiki.openstreetmap.org/wiki/Osmdroid) seems to be the most popular solution for achieving this, and is hopefully not too hard to include.

**Comment by g1lg1l** [comment]
We will do it! But after we have fixxed some other problems on the local folder!

**Comment by g1lg1l** [comment]
I have implement the map on details dialog in this [commit](https://github.com/HoraApps/LeafPic/commit/59c9f5241f9011e4d92652b6d2acabde3d4c9cbc)! tell me if you see bugs! stay tuned!;)

**Comment by utack** [comment]
It is not a big fan of compiling at the moment, but that might be my fault

> /LeafPic-master/app/src/main/java/com/horaapps/leafpic/PhotoPagerActivity.java:543: error: variable Delete_dialogLayout might not have been initialized
>                 final LinearLayout llLocation=(LinearLayout)Delete_dialogLayout.findViewById(R.id.ll_location);
>                                                             ^
> 1 error
> :app:compileDebugJavaWithJavac FAILED

**Comment by g1lg1l** [comment]
This is what happen when you don't test your code...haha, im' sorry, fixxed [here](https://github.com/HoraApps/LeafPic/commit/218dd45ed7d2c704f3935b27e9d5d03c1ae823fc)!:)

**Comment by utack** [comment]
NVM, figured out how to build

**Comment by utack** [comment]
It works now, thanks for adding it so quickly.

**Comment by 51114u9** [comment]
Please, use GEO URI scheme standard ([rfc5870](https://tools.ietf.org/rfc/rfc5870))... `geo:latitude,longitude?z=zoom`. Source code in line [739](https://github.com/HoraApps/LeafPic/blob/fab11df5d8a8cc5d8969c1252150cc76db56295b/app/src/main/java/com/horaapps/leafpic/PhotoPagerActivity.java#L739) is (only) for Google and related. 

Maybe better z value is z=17, because show details of map ~300m (context) near of point. Using z value, force highest (closest) zoom level, if maps app is opening before leafpic the zoom level is not changed, only change the location.

Reference: [Android Available Intents](https://developer.android.com/guide/appendix/app-intents.html), [Android Show location on a map](https://developer.android.com/guide/components/intents-common.html#Maps), and [Discussion of implement `geo:` in OpenStreetMap](https://github.com/openstreetmap/openstreetmap-website/issues/799).
