### ISSUE TITLE
Files Not Recognized

### ISSUE THREAD

**Issue by TinfoilSubmarine** [UnevenSoftware/LeafPic#190]
When a file has an extension with capital letters (examples: .JPG, .Jpg, .jPg, etc.) the file is not recognized by LeafPic.

**Comment by JunCTionS** [comment]
Ah you're right! I thought it might be some weird issue with SD permissions in my case, I'm happy this is the case as it is easier (I'm seeing this in a folder with many .JPG images downloaded from my camera and the occasional .jpg edited on the phone).
I don't have the proper setup to do a pull request, but I guess this would be fixed by changing:
 LeafPic/app/src/main/java/com/horaapps/leafpic/Base/ImageFileFilter.java
where it says:  
if (filename.endsWith(extension)) 
to: 
if (filename.toLowerCase().endsWith(extension))

**Comment by dnldsht** [comment]
Done, will be available in the next release!
Stay tuned

**Comment by dnldsht** [comment]
fixed with this [release](https://github.com/HoraApps/LeafPic/releases/tag/v0.4)
