### ISSUE TITLE
[Bug] Loading LeafPic takes forever

### ISSUE THREAD

**Issue by BlackLotus** [UnevenSoftware/LeafPic#221]
When starting LeafPic fresh it takes over 15 seconds to show the galleries. (For me it takes constant 17 secs and in this time only shows the logo)
All in all I got a 40 Gallery-Folders and around 4000 images.
Other gallery apps I tested (google photos, stock gallery and simple gallery) take around 1-2 seconds.
Didn't yet look at the code for this.

**Comment by dnldsht** [comment]
@BlackLotus Reduced drastically the waiting time on launch in the coming release! :D

EDIT: if you want to try build the develop branch (1st time take long as now other times it takes less).

**Comment by BlackLotus** [comment]
Tried both master and develop, but didn't really notice any speed boost (even after the second start)
Will take a closer look at it tomorrow after work.

**Comment by xtj-9182** [comment]
I have noticed this as well. I have around 3000 folders with around 15 to 20 images each. For me it helped to exclude folders that I didn't need since most of those are from manga chapters. 

Anyway I was thinking instead of loading all albums at once load the first few thumbnails/albums and as soon as they are loaded display them to the user. It could be shown with a loading spinner so that the user knows that something is happening. This way the user can already do something this makes it seem like the loading time is lower than it is. (and it's also what some other image viewers are doing)

**Comment by dnldsht** [comment]
@xtj-9182 @BlackLotus i forgot that it isn't enabled by default. you have to build this [commit](https://github.com/HoraApps/LeafPic/commit/14e9ef575f2516c9575d6d4aba7514025f5a2d16) and disable the "Auto update media" setting

**Comment by xtj-9182** [comment]
using around ~300 image folders it takes around ~33 Seconds on _first_ cold start. Every cold start after this takes around ~2 Seconds due to the new serialization of the album arraylist.

pretty good but that initial cold start has me a little worried.

Edit: also not related but I'm seeing `I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.`

**Comment by dnldsht** [comment]
@xtj-9182 33 seconds are a lot, in my nexus 5 firs cold start takes ~5 seconds. do you have a SD card?

BTW I'm gonna add a setting that allow fetching media from media store so it should be more faster. 

> also not related but I'm seeing I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead

I have no idea where it is located in code,  I'm getting this warming since first release

**Comment by xtj-9182** [comment]
@dnldsht 
Yes most of my media is on my sd card. Fun side note: when I first found out about leafpic around v0.3 I thought it wasn't working since the initial start up is so slow.

what are your thoughts on my initial proposal ?

> instead of loading all albums at once load the first few thumbnails/albums and as soon as they are loaded display them to the user. It could be shown with a loading spinner so that the user knows that something is happening. This way the user can already do something this makes it seem like the loading time is lower than it is. (and it's also what some other image viewers are doing)

no idea if that would still be needed after your media store fetching optimizations.

about app:theme: too bad I thought it would be an easy fix :(.

**Comment by BlackLotus** [comment]
Oh yeah just wanted to give my input as well.
The newest build certainly is fast enough and LeafPic is now again my main gallery app.
Thanks :+1:
