### ISSUE TITLE
Disabling EXIF Interface to load thumbnails speeds up general case performance (Debate)

### ISSUE THREAD

**Issue by venupai** [UnevenSoftware/LeafPic#243]

**Comment by dnldsht** [comment]
I tried to get Thumnails with the MediaStore.Images.Thumbnails.queryMiniThumbnail() and with the ExifInterface during the onBindViewHolder() and both slow down it.
Now I'm testing without thumbnails and performance are increased but I have to test it with a lot of larger images.

in your opinion is a good idea prefetch thumnails so I haven't to fetch them when I'm gonna display them?

**Comment by wyatt8740** [comment]
I don't really like to suggest this, but what about a thumbnail cache database?
You'd want to be aggressive in cleaning it up when images no longer exist, though, and you'd want to have it save modification times so it updates if the image was modified.

**Comment by dnldsht** [comment]
@wyatt8740 there is a thumnail cache database in the android system accesible via MediaStore.Images.Thumbnails.queryMiniThumbnail(), but also that is slow if you have to query a thumnail for every image that you have to display.

**Comment by metinkale38** [comment]
currently first ExifInterface.getThumbnail is called and then the result passed to Glide.

Glide normally does the caching stuff, but like this, it always has to load the image from the byte array, and probably also caches them, but can't use the cache later...

I think the best approach would be, to create a custom Glide Model Loader (see https://futurestud.io/blog/glide-module-example-accepting-self-signed-https-certificates for a similar task), so it only loads the Exif Thumbnail, if it cant find it in its own cache.

There is also a MediaStoreThumbFetcher in Glide, if you want to use the MediaStore Thumbnail: https://github.com/bumptech/glide/blob/3.0/library/src/main/java/com/bumptech/glide/load/data/MediaStoreThumbFetcher.java

There are several ways, but it is generally not a good idea, to pass the Byte Array to Glide, because Caching won't work, as it should.
