### ISSUE TITLE
Artwork preview display in video

### ISSUE THREAD

**Issue by Chic999** [UnevenSoftware/LeafPic#259]
We use itunes to add up artwork and poster to music videos and movies

**Comment by wyatt8740** [comment]
I have no idea what you want; are you saying you want this to be _itunes compatible_?

**Comment by Chic999** [comment]
An artwork will be shown in videos. I can send you screenshots

**Comment by wyatt8740** [comment]
you mean as a thumbnail?

iTunes shouldn't have anything to do with this since IIRC itunes saves thumbnails in a proprietary encrypted database file and not in the video itself.

**Comment by dnldsht** [comment]
@wyatt8740 I also don't understand what she mean!

**Comment by wyatt8740** [comment]
@dnldsht I _think_ this person wants movie posters or other embedded thumbnail images to be used as the previews for video files that contain them. The iTunes thing is misguided.

Matroska (.mkv) videos can contain thumbnails, for example; see https://matroska.org/technical/cover_art/index.html .

Since standard MP4's don't contain any provision for this, Apple used a database file to contain thumbnails that would be used as preview images on their devices, like iPods. If my iPod didn't run Rockbox now, I'd show what I mean :\

(I stopped using windows and itunes regularly many years ago, so it would be a big hassle to restore Apple's firmware to it)
