### ISSUE TITLE
[Improvement] File Manager Hidden

### ISSUE THREAD

**Issue by ghost** [UnevenSoftware/LeafPic#285]
Can LeafPic hide pictures from File Managers?

**Comment by brandonio21** [comment]
I'm not too sure about the details of hiding things in LeafPic currently. I know there may be some confusion because there is _exclusion_, which puts the path of the folder/picture in a database and just hides it from the user when using LeafPic.

There is also _hiding_, which presents some sort of warning about a `.nomedia` file, but I don't really know how it is implemented.

I think the best way to hide things from other File Managers would be to use the dot convention (ie hiding "pr0n/" would move it to ".leafpic-hidden/pr0n"). I just checked with Solid Explorer and it does not seem to pick up files/folders with "." in front of them (Linux hidden files)

So maybe we could think about changing the hiding algorithm to instead move the directories into a ".leafpic-hidden" directory. But I don't know about how the current hiding works. Maybe @Mow3l or @dnldsht  can speak more on it.

**Comment by touzainanboku** [comment]
@brandonio21 most file managers, including Solid, will allow you to view folders with a dot at the start of their name if you enable "show hidden folders", so that's not the way to go.

I'm fairly certain the current hiding feature puts a .nomedia file in the corresponding folder, which tells the media store to not display the media files in that folder. Any app using the media store to view media files will not display these files. 

In both solutions, a file manager that allows you to see hidden files/folders (the ones that have names starting with a dot) will still allow you to see the images.

I think the only way you can make the images unviewable (for a lack of a better word) to a file manager is to encrypt it or something. That way the file manager could still technically see the encrypted file, but it wouldn't be viewable as a photo since the file manager can't decrypt it.
