### ISSUE TITLE
From 0 to 100 percent, how likely are you of...

### ISSUE THREAD

**Issue by jahirfiquitiva** [UnevenSoftware/LeafPic#341]
How likely are you of, if I share a long and really descriptive feedback (bugs, requests, suggestions etc), actually implementing it or making it real?

I like the app, although I think many things could be improved and/or changed, so, I wanted to share feedback.

Really detailed one, but some people are just full-of-themselves and they just don't accept this kind of criticism.

So I just don't want to waste my time.

Thanks. And great work.

**Comment by dnldsht** [comment]
Hey, I accept critics, I know that this project need a lot of work, it has many bugs and lacks a lot of feature.  I'm working on it when I have free time (I'm still a student and recently got a kind of part-time job).

I'd like to hear your feedback, but don't waste time reporting stuf that it is already reported or for 'impossible' feature.

at [waffle.io](https://waffle.io/HoraApps/LeafPic) you can find all bugs and feature requests to avoid duplicate! otherwise you can email me!

Cheers!

**Comment by jahirfiquitiva** [comment]
@dnldsht 
Thanks, I will report them in the nexts days. :)
