### ISSUE TITLE
Thumbnail 404

### ISSUE THREAD

**Issue by ouafnico** [UnevenSoftware/LeafPic#364]
For my camera folder, I got a 404 red picture as thumbnail for the folder.

**Comment by xtj-9182** [comment]
this happens to me too, initially I suspected that it had to do with the serialization of the albums ArrayList but this seems to happen even when I delete the albums.dat file.

I can reproduce this with the latest build (commit 2925516579b6dd60ae7af8f443cbfbd01eb2cd20)

I use a Screenshot app called Screenshot Easy (https://play.google.com/store/apps/details?id=com.icecoldapps.screenshoteasy&hl=en) when I take a Screenshot and then delete it after it's taken using Screenshot Easy I then get "blank images" in leafpic. Which means that the deleted Screenshots somehow appear as "blank images" in Leafpic and when one of them is in the first place of an album, say if you sort by date, the thumbnail of the album will display 404 with a red background.

here is a picture of the blank images, basically they look like images that haven't been loaded.

![2016_11_08_13 37 24](https://cloud.githubusercontent.com/assets/9414008/20099638/cb990012-a5b9-11e6-987f-9dab3e2f4f5b.png)

So somehow leafpic displays deleted images, I have no idea why since these images are definitely deleted, they don't show up when I browse the directory with an explorer app. I have also swiped down to update to see if that would change anything but alas it didn't do anything, yet it does seem to update correctly for other images, when I delete an image externally using an explorer app it will show this change in leafpic when I swipe down.

**Comment by dnldsht** [comment]
@xtj-9182 can you try to enable the alternative provider ad tell me if they are still there?

**Comment by xtj-9182** [comment]
Interesting it's only happening with the default Provider when I use the Alternate Provider everything works fine. So the default Provider seems to cause it for me.

edit: Is there a reason why the alternate Provider isn't the default it seems to work faster too for me.

**Comment by dnldsht** [comment]
The MediaStore on android is a mess, because app have to tell the system(MediaStore) if they update/delete/create files and many developers dont care about it.

The alternative provider may be slower sometimes if you have many folders with images or even a slow SD card, beacuse it looks recursively for media.

I'm thinking for a solution to update the MediaStore using some alternative provider info.

**Comment by Sam-C-Dev** [comment]
I too get a 404 for my Screenshots _and_ Download folder.  Also, I normally would hide the Screenshot folder in QuickPic, but with LeafPic I can't hide it. There is some private stuff in there.
I'm am using the standard screenshot method with Galaxy, not a 3rd party app.

![2017-01-31 13_06_00-clipboard](https://cloud.githubusercontent.com/assets/25025399/22480184/21ffe824-e7b6-11e6-8b0c-048ea5aca131.png)

**Comment by emdete** [comment]
> The MediaStore on android is a mess [...] I'm thinking for a solution to update the MediaStore using some alternative provider info.

for deleted images it's enough to just issue a rescan. i would suggest to use the MediaStore but check the image for existance and date. if either fails kick off a scan and the MediaStore is updated fine. something like this should be fine:

```
Intent intent = new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE);
intent.setData(Uri.fromFile(file));
sendBroadcast(intent);
```

detection of new media not in the store may be a bigger problem as one has to iterate through the filesystem...
