### ISSUE TITLE
instead of backbutton showing menu button in action bar

### ISSUE THREAD

**Issue by sohampandya00** [UnevenSoftware/LeafPic#492]
when we click on album (local folder), sometimes it shows menu button in actionbar instead of backbutton.

**Comment by dnldsht** [comment]
Are you on the dev branch?

**Comment by sohampandya00** [comment]
i did clone project from https://github.com/HoraApps/LeafPic.git

**Comment by dnldsht** [comment]
Yeah, you. should be in the dev branch, check it out with `git branch`.

I also discovered that, trying to find out why!
Do you also have problems with done icon (when you are selecting) ?

**Comment by calvinnor** [comment]
Could you point me to a document saying we should call super (onCreateOptions, onPrepareOptions) after our custom code?

**Comment by dnldsht** [comment]
I found nothing that says to call it later, but in many stack overflow
questions they call them later

On Jan 21, 2018 6:39 AM, "CalvinNor" <notifications@github.com> wrote:

Could you point me to a document saying we should call super
(onCreateOptions, onPrepareOptions) after our custom code?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/HoraApps/LeafPic/issues/492#issuecomment-359225519>,
or mute
the thread
