### ISSUE TITLE
Resolution shows as ¿x?

### ISSUE THREAD

**Issue by carusooo** [UnevenSoftware/LeafPic#525]
Image resolution is showing as ¿x? for all images on my phone and on emulator.

I added a check to load the height/width from EXIF if the call to BitmapFactory didn't set width/height properly, but that doesn't resolve the issue when images do not contain EXIF data. 

Any thoughts on what could be causing this? I am happy to chase down any ideas and try to make a fix :)

![screenshot_1520215900](https://user-images.githubusercontent.com/33580338/36954550-b4fe9bca-1fd7-11e8-9f4b-e945160107b5.png)

**Comment by DannyThompson** [comment]
I opened a PR on this that you can find here:  https://github.com/HoraApps/LeafPic/pull/543 Essentially, we just need to get the Media's bitMap info. Since for some reason Media.getBitMap is annotated as Deprecated, I handled it by passing the media through to the Metadata, and handling it this way.  If you can come up with a more elegant solution, be my guest! Just thought I'd suggest a fix for now since I noticed that this has been open for a while :}

**Comment by zhao-gang** [comment]
@DannyThompson Hi, I am also trying to fix this bug in #544 :-) My solution is passing a fresh new input stream to BitmapFactory.decodeStream(), since the function can't parse the input stream already used by ImageMetadataReader.readMetadata().

**Comment by dnldsht** [comment]
fixed by #544
