### ISSUE TITLE
App crashes when i tried to open bigger sized folder. 

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [UnevenSoftware/LeafPic#538]
#### Expected behavior
Upon clicking on bigger sized folder to open. It must able to open folder. 

#### Actual behaviour
When i tried to open bigger sized folder, app crashes. 

#### How to reproduce
Install app from f droid. 

Open app. 

Click on folder containing bigger sized images. 

It will crash while clicking on folder. 

* Browser: LeafPic[Beta]
* Version:0.6-Beta-1
* Operating system:5.1.1

#### Recording Of The Bug
https://youtu.be/cBL-j2cRjtY
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@peerzadazeeshan/app-crashes-when-i-tried-to-open-bigger-sized-folder">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by calvinnor** [comment]
@PeerzadaZeeshan Hello, thanks for reporting this!

It's a little difficult to identify the actual cause of the crash at your end. 
We're guessing it's an Out Of Memory problem, since you did specify that it's a large album.

But it could be some other issue lurking in our code.

Could you possibly reproduce the issue and grab a logcat for us? Would be very helpful to assist you that way.

When LeafPic crashes, "Unexpected error occurred" screen appears. You can either screenshot the stack trace option there, or use an app like MatLog to grab the logs. Please attach them on this issue and ping me here when done.

Thanks a lot for your assistance in making LeafPic a better gallery! :blush:
