### ISSUE TITLE
Request for copywriting 

### ISSUE THREAD

**Issue by princekelly1** [UnevenSoftware/LeafPic#561]
Hi, I use your project and would love to contribute to its development by writing a FAQ section, about us and privacy policy for the project to be merged into the documents of the project and added to the app for users. This would definitely improve the project and help users.

**Comment by calvinnor** [comment]
@princekelly1 Hello!

Since we're open-source and don't send / receive any user info over the internet, I don't know if we really need a Privacy Policy.

However, an FAQ section & About Us seems like a really good plan. @dnldsht What do you think?

Thanks for your inputs, we'd love to see your contribution to the project :)

**Comment by princekelly1** [comment]
Hi
Thanks, I would make a pull for about us and FAQ soon, for yout review
